### ISSUE TITLE
Test asset failing AMP document size limit

### ISSUE THREAD

**Issue by joshcoventry** [bbc/simorgh#8104] opened 2020-10-13 14:10 UTC
**Is your feature request related to a problem? Please describe.**

Tests are failing because the test asset fails the AMP document size check:

`
/mundo/23263889
FAIL
line 1, col 7332: The author stylesheet specified in tag 'style amp-custom' is too long - document contains 79691 bytes whereas the limit is 75000 bytes. (see https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#maximum-size)
`

**Describe the solution you'd like**

The document should be 75000 bytes or less.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by andrewscfc** [comment] 2020-10-14 07:53
Investigating this I have found most of the unused css comes from css comments introduced by styled components (http://localhost:7080/mundo/23263889.amp):
![image](https://user-images.githubusercontent.com/9645462/95959598-95bb5780-0dfa-11eb-8d6a-183c4bd2f94d.png)

I followed this guide to identify unused css: https://developers.google.com/web/tools/chrome-devtools/coverage

I cannot currently see any options to remove these in babel-plugin: https://styled-components.com/docs/tooling#babel-plugin

**Comment by andrewscfc** [comment] 2020-10-14 10:40
Blocked for now on our upgrade to Emotion @neildoughty confirmed a relatively small number assets are affected at the moment; we hope that the upgrade to emotion may:
- automatically fix this by compacting our css
- allow more flexibility to solve this problem through using a better maintained and supported library

![image](https://user-images.githubusercontent.com/9645462/95978449-1a65a000-0e12-11eb-96f5-5c1e4a6e1ed3.png)

**Comment by karinathomasbbc** [comment] 2020-11-03 21:22
I don't think that the migration to Emotion will have any impact on this - the checks are still failing - see https://github.com/bbc/simorgh/pull/8171/checks?check_run_id=1342629376#step:6:1

**Comment by andrewscfc** [comment] 2021-01-08 08:16
https://github.com/bbc/simorgh/pull/8681 was an attempt to resolve the issue for `/mundo/23263889` but did not decrease the amount of css by enough for to be valid. The description on this PR https://github.com/bbc/psammead/pull/4179 describes further complex work that could be investigated to decrease the css further; we decided to look into how big the problem is before commiting to any more complex work.

@neildoughty checked our google dashboards and found the following:
> For Mundo there are still 2.5k invalid AMP assets, against 80k valid ones.

This indicates relatively small number of assets are affected.

We have decided to take the following actions and close this issue:
- Merge https://github.com/bbc/simorgh/pull/8681 to potentially decrease the number of invalid assets, particularly those on the boundary of the 75000 bytes limit
- Create this PR https://github.com/bbc/simorgh/pull/8684 that prevents `/mundo/23263889` from failing the amp validation - other services Story pages will continue to be amp validated so the test coverage remains.

**Closed as completed** 2021-01-11 12:29 UTC
Labels: bug, ws-articles
