### ISSUE TITLE
Lighthouse Recommendation - Ensure images display with the correct aspect ratio

### ISSUE THREAD

**Issue by FK78** [bbc/simorgh#6989] opened 2020-06-22 17:46 UTC
**Is your feature request related to a problem? Please describe.**
Parent issue: https://github.com/bbc/simorgh-infrastructure/issues/1088

If a rendered image has an aspect ratio that's significantly different from the aspect ratio in its source file (the natural aspect ratio), the rendered image may look distorted, possibly creating an unpleasant user experience.

A run against https://www.test.bbc.com/arabic:

<img width="891" alt="Screenshot 2020-06-24 at 17 49 49" src="https://user-images.githubusercontent.com/34196381/85598100-c94f5780-b63a-11ea-9660-b21d15b3fe3d.png">

Report: https://lighthouse-dot-webdotdevsite.appspot.com//lh/html?url=https%3A%2F%2Fwww.test.bbc.com%2Farabic

**Describe the solution you'd like**
https://web.dev/image-aspect-ratio/#ensure-images-display-with-the-correct-aspect-ratio

Try specifying higher density images in the src set and see if this clears the LH audit issues, more info on this can be found here http://thenewcode.com/944/Responsive-Images-For-Retina-Using-srcset-and-the-x-Designator

**Describe alternatives you've considered**

**Testing notes**
- re-run the LH test to ensure the audit now passes

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by chris-hinds** [comment] 2020-06-25 14:41
We are also seeing this on live on at least two service; Arabic & Pidgin 
![image](https://user-images.githubusercontent.com/14273378/85741269-2eb64d80-b6fa-11ea-916c-193898d8eaf3.png)

Do we know what these values mean and what they should be `Displayed size | Actual size | Expected size`

LH seems to expect the image to be almost 3 times the current displayed size.

**Comment by chris-hinds** [comment] 2020-06-25 14:45
Should we be also rendering retina style images in the image src set using `x2` to specify higher density imagers for retina displays. http://thenewcode.com/944/Responsive-Images-For-Retina-Using-srcset-and-the-x-Designator

**Comment by joshcoventry** [comment] 2022-01-12 11:50
Can't reproduce this now after running a new Lighthouse report against test Arabic, closing.

**Closed as completed by joshcoventry** 2022-01-12 11:50 UTC
Labels: investigation, low-priority, performance, technical-work, cross-team
