### ISSUE TITLE
Render more readable snapshots for components

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#3878] opened 2019-09-19 14:55 UTC
**Is your feature request related to a problem? Please describe.**
We should make use of psammead's test helpers to render more readable snapshots than what we currently have so that we can more easily spot unexpected changes in styles and markup. We should do this for these components initially and then consider other components:

- `src/app/containers/App/index.test.jsx`
- `src/app/containers/FrontPageMain/index.test.jsx`
- `src/app/containers/FrontPageSection/index.test.jsx`
- `src/app/containers/Navigation/index.test.jsx`
- `src/app/containers/StoryPromo/IndexAlsos/index.test.jsx`
- `src/app/containers/StoryPromo/LinkContents/index.test.jsx`

**Describe the solution you'd like**
Replace any shallow snapshot rendering with `@bbc/psammead-test-helpers` `shouldMatchSnapshot` function. This renders a more readable snapshot with things like meta tags, scripts, styles.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by FK78** [comment] 2019-09-19 15:03
Is this not very similar to #3264?

#3842
#3854

**Comment by FK78** [comment] 2019-09-19 15:21
Duplicate of #3264.

**Closed as completed by FK78** 2019-09-19 15:21 UTC
Labels: Refinement Needed
