### ISSUE TITLE
Pass locale correctly to the relative timestamps in Persian.

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#1969] opened 2019-06-18 10:10 UTC
**Is your feature request related to a problem? Please describe.**
We need to update our Gregorian timestamps to support Persian, this includes using different numerals and right-to-left support.

**Describe the solution you'd like**
When viewing an article in Persian, the timestamp should: 
- Use Eastern Arabic numerals (possibly returned when using moment's `fa` locale) e.g. <span dir="rtl">۱۸ ژوئن ۲۰۱۹</span>
- Be right-to-left (should be fixed by adding dir on page level in #611)
- Have onscreen and offscreen translations in Farsi for `Updated` text
- When time is updated, the updated timestamps should all read in Farsi

**Describe alternatives you've considered**

**Testing notes**
Regression on timestamps in News/Persian. Checking with someone who reads Persian whether the date is correct. 

Dev insight: Cypress and unit tests with updated snapshots should ensure translations are correct.

**Additional context**

**Comment by dr3** [comment] 2019-06-18 10:14
~Duplicate of https://github.com/bbc/simorgh/issues/1567~

**Comment by 12** [comment] 2019-06-18 10:15
No it's not @dr3. This is still the Gregorian calendar, #1567 is to investigate non-Gregorian (Jalili) calendars. We still need to translate the Gregorian calendar to Farsi.

**Comment by dr3** [comment] 2019-06-18 10:18
>Use Eastern Arabic numerals (possibly returned when using moment's fa locale)

In that case, this is true :) and Eastern Arabic numerals will be done in https://github.com/bbc/simorgh/issues/1663

**Comment by greenc05** [comment] 2019-07-17 09:39
@rhell please could you expand on 'Have onscreen and offscreen translations in Farsi for Updated text'? What are the offscreen requirements??

**Comment by 12** [comment] 2019-07-17 09:54
@greenc05 I think I was referring to the relative timestamp e.g. `Updated 25 mins ago`. Looking at our UX though I can't see any notes for offscreen text... I'll try and remember what I meant here 😛

**Comment by RayNjeri** [comment] 2019-07-18 06:51
When these two fields are updated in the local fixture data, We get time updated in English instead of in Farsi which is the expected output.

```
"lastPublished": 1535122662000,
"lastUpdated": 1535122662000,
```

<img width="1397" alt="Screen Shot 2019-07-17 at 14 11 09" src="https://user-images.githubusercontent.com/27012452/61435394-06966a00-a941-11e9-8bdc-d1d751cd58f1.png">

**Comment by RayNjeri** [comment] 2019-07-23 09:24
Duplicate of  https://github.com/bbc/psammead/issues/1161
https://github.com/bbc/psammead/pull/1067 fixes this issue

**Closed as completed by RayNjeri** 2019-07-23 09:24 UTC
Labels: ws-articles
