### ISSUE TITLE
Test that messages are logged when no media is present in MAPs

### ISSUE THREAD

**Issue by pharingee** [bbc/simorgh#5923] opened 2020-03-19 08:48 UTC
**Is your feature request related to a problem? Please describe.**
There are no tests to ensure that messages are logged when there is no media or when translations are not found

**Describe the solution you'd like**
Write tests to test the logging functionality

**Describe alternatives you've considered**
Leaving these logs untested could have them changed in the future unintentionally.

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by gavinspence** [comment] 2020-07-27 16:09
Do we still need this @pharingee ?

**Comment by pharingee** [comment] 2020-08-11 06:54
Yes, the test for this isn't written so we need to write it

**Comment by ryanmccombe** [comment] 2020-08-11 20:25
We do seem to have unit tests for both of these things

- Tests for no media block logging: https://github.com/bbc/simorgh/blob/latest/src/app/routes/cpsAsset/getInitialData/processUnavailableMedia/index.test.js#L93
- Tests for no translation logging: https://github.com/bbc/simorgh/blob/latest/src/app/pages/MediaAssetPage/MediaMessage/index.test.jsx#L41-L52

This is a very old issue and these things were probably fixed in later PRs - I suggest we close this if we can get confirmation that those tests are what the issue is asking for

**Comment by karinathomasbbc** [comment] 2020-08-13 15:28
Happy that this has been covered by existing tests - let's close it!

**Closed as completed by karinathomasbbc** 2020-08-13 15:28 UTC
Labels: Refinement Needed, ws-media, technical-work, Weekly goal
