### ISSUE TITLE
Related Content visited links not differentiated in Chrome

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#5507] opened 2020-02-11 16:37 UTC
**Describe the bug**
On latest Chrome on desktop (and possibly other browsers), when you have visited one of the 'related content' links at the bottom of CPS assets the visited link is shown in the same colour. On latest Firefox, Internet Explorer and Safari it is shown a lighter grey.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a photo gallery using Chrome
2. Click on one of the Related Content links at the bottom
3. Go back, note no visited link colour change (compare Firefox/Safari)

**Expected behaviour**
Consistent link visuals across browsers/devices.

**Screenshots**
<img width="452" alt="Screenshot 2020-02-11 at 16 34 07" src="https://user-images.githubusercontent.com/11161809/74257215-6c3ab100-4cec-11ea-84ff-ff0439c58d69.png">

**Desktop (please complete the following information):**

- OS: macOS 10.14
- Chrome 80

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
Links on front pages do not exhibit the same inconsistency therefore it seems likely the problem is specific to Related Content.

**Comment by 12** [comment] 2020-02-20 13:09
- Chrome 82.0 Canary
- Chrome 79.0
- Firefox 75.0a Nightly
- Safari 12.1.2

I've been unable to reproduce this problem. Upon visiting a previously unvisited link, when I then return to the original page, the newly visited link turns grey. This behaviour occurs in all the browsers listed above.

![image](https://user-images.githubusercontent.com/7690572/74936503-2794d100-53e2-11ea-859a-74a50232eb50.png)

**Comment by paruchurisilpa** [comment] 2020-02-24 15:03
I am able to recreate this on Live:

URL --> https://www.bbc.com/pidgin/50913502

1.Go to the above link in ff
2.Scroll to the bottom of the page
3.Click on Related link "Christmas: Why Santa Claus dey always wear red and white"
4.Click on back
5.The visited link color changes to grey in ff but stays the same in Chrome

**Comment by paruchurisilpa** [comment] 2020-02-24 16:15
I think I was able to recreate this as I have accidentally started a incognito window rather than a new window and in incognito tracking shouldn't be allowed, so thats why I was able to recreate this issue.

I will close this issue for now and when we do the next ally swarm will keep an eye for this and open a new ticket if this is still an issue..

**Closed as completed** 2020-02-26 11:22 UTC
Labels: bug, ws-articles, ws-media
