### ISSUE TITLE
Broken Javascript on Live on Safari 13.x 

### ISSUE THREAD

**Issue by skwong25** [bbc/simorgh#9749] opened 2021-12-16 10:01 UTC
**Describe the bug**
Javascript seems to be broken on Safari 13.x and older* (across MacOS desktop & iOS mobile) 
i.e no cookie banner & images not loading, drop-down menu not working

This was found testing on the following BrowserStack devices: MacOS Catalina,  iPhone 11 Pro Max, iPhone XS.

*Noticed also on Safari 12, 11 and 10 - but these are not Level A/B supported browsers so assume not that important. 
Same issue is not appearing on Safari 15, 14. 

**To Reproduce**
1. Go to webpage, eg: https://www.bbc.com/afaanoromoo

**Expected behaviour**
- Cookie banner should appear
- Images below main image should load up
- Drop-down menu (top-left) should expand upon click 

**Screenshots**

**Desktop / Mobile:**

- OS: MacOS Catalina,  iPhone 11 Pro Max, iPhone XS.
- Browser: Safari 13.x

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Checklist**
- [ ] (BBC contributors only) This issue follows the [repository use guidelines](https://github.com/bbc/simorgh-infrastructure/blob/latest/documentation/repository-guidelines.md)

**Additional context**

**Comment by jroebu14** [comment] 2021-12-29 14:37
This is a known bug in Safari https://bugs.webkit.org/show_bug.cgi?id=171041

This is caused by a [recent update to our babel configuration](https://github.com/bbc/simorgh/pull/9584/files#diff-b417af757044d72f7b8d629728f646d5cf42b8be85ace886526f50bb8c7645a7R43).

I'm able to fix the bug by [altering our babel config to support Safari 10+](https://github.com/bbc/simorgh/pull/9760) however it adds over 50k to our bundle size.

I'd like to find out how many users are affected before applying the fix.

**Comment by aeroplanejane** [comment] 2022-01-05 12:06
@jroebu14 checked the stats (think our browser support list requires updating) 
Older versions of safari 13.x all the way to 1.0x accounted for 1.4% (11,683,535 visits) of total traffic in the last quarter. Safari 14.x and 15.x accounted for 10% of all traffic 73,062,675 visits

**Comment by jroebu14** [comment] 2022-01-05 12:20
Thanks for looking into this @aeroplanejane!

That's quite a lot of visits so I think we need to support Safari 13 if you agree.

**Comment by aeroplanejane** [comment] 2022-01-05 13:13
Will the fix for safari 13 also fix safari 12 and 11? They have actually had higher levels of traffic over the same time period! 
Do we think that fixing this will add considerably more page weight to all other browsers? Yeah, feels like something we should fix but I'm sorry it's adding more weight... cc @gavinspence

**Comment by jroebu14** [comment] 2022-01-05 13:23
Yeh it will fix 11 and 12 too. It adds roughly 50k to the total page weight. I don't think we can do much about that tbh

**Comment by aeroplanejane** [comment] 2022-01-10 10:13
Agreed this should be fixed. cc @gavinspence

**Closed as completed** 2022-01-13 14:34 UTC
Labels: bug
