### ISSUE TITLE
Variant redirects not working for amp urls

### ISSUE THREAD

**Issue by mykeels** [bbc/simorgh#4710] opened 2019-11-18 13:58 UTC
**Describe the bug**
The [default variant redirect feature](https://github.com/bbc/simorgh/pull/4567) does not work when the URL has the `.amp` suffix.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.test.bbc.com/ukchina.amp
2. Notice the 500 status code

**Expected behaviour**
The page should load in amp mode.

**Screenshots**

![image](https://user-images.githubusercontent.com/11996508/69058242-96dddc00-0a13-11ea-8936-ef00914f2eda.png)

**Testing notes**
Regression tests for frontpage, and article urls, with expected redirects

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by PriyaKR** [comment] 2019-11-25 15:56
Regression on articles, frontpage looks good.For service with variants i am not seeing the cookie value for these cookies ckps_chinese,ckps_serbian being set.

**Comment by PriyaKR** [comment] 2019-11-26 11:34
Looks like the cookies work for variant is not yet done https://github.com/bbc/simorgh/pull/4755
Looks good to me can be merged.
http://localhost:7080/zhongwen.amp redirects to http://localhost:7080/zhongwen/simp.amp
accordingly for serbian and UKchina to the default variant.

**Closed as completed** 2019-11-29 14:46 UTC
Labels: bug
