### ISSUE TITLE
V1 Images Layout

### ISSUE THREAD

**Issue by bcmn** [bbc/simorgh#1319] opened 2019-02-19 08:40 UTC
**Is your feature request related to a problem? Please describe.**
UX have updated the designs regarding images.

**Describe the solution you'd like**
In the data feed, we are provided the width and height of the original uploaded image.

There is a minimum width & height of 100px on article images.

**GEL Group 1 (0-399px)**
**GEL Group 2 (400-599px)**
If **any** image is wider than all 6 columns, it is displayed "full-bleed", with the content stretched to the edges of the viewport.

If **any** image is smaller than all 6 column widths, the image is displayed left aligned, at its original size, starting column 1.

**GEL Group 3 (600-1007px)**
If a landscape image is wider than all 6 columns, it is displayed "full-bleed", with the content stretched to the edges of the viewport.

If a landscape image is smaller than all 6 column widths, the image is displayed left aligned, at its original size, starting column 1.

Portrait images are displayed left-aligned, in the first 4 of the 6 columns. They have a max width of 4 columns.

Square images are displayed left-aligned, in the first 5 of the 6 columns. They have a max width of 5 columns.

**GEL Group 4 (1008-1279px)**
Landscape images are displayed left-aligned, in 6 of the 8 columns, starting column 2. They have a max width of 6 columns.

Portrait images are displayed left-aligned, in 4 of the 8 columns, starting column 2. They have a max width of 5 columns.

Square images are displayed left-aligned, in 5 of the 8 columns, starting column 2. They have a max width of 5 columns.

**GEL Group 5 (1280px+)**
Landscape images are displayed left-aligned, in 12 of the 20 columns, starting column 5. They have a max width of 12 columns.

Portrait images are displayed left-aligned, in 8 of the 20 columns, starting column 5. They have a max width of 8 columns.

Square images are displayed left-aligned, in 10 of the 20 columns, starting column 5. They have a max width of 10 columns.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment] 2019-02-25 11:05
Blocked on https://github.com/bbc/simorgh/issues/1318

**Comment by dr3** [comment] 2019-03-06 11:08
To be confirmed and refined with @jimjohnsonrollings about how full bleed works

**Comment by ChrisBAshton** [comment] 2019-03-12 13:20
No longer blocked on other work, but have assigned to Jim to answer Drew's question above.

**Comment by jimjohnsonrollings** [comment] 2019-03-13 09:46
As discussed, full bleed only on Groups 1-3, there is no requirement at this stage for full bleed on Groups 4-5

**Comment by sareh** [comment] 2019-05-22 08:58
Closed since this is part of this issue now: https://github.com/bbc/simorgh/issues/1751

**Closed as completed by sareh** 2019-05-22 08:58 UTC
Labels: blocked, Refinement Needed, ws-articles, articles-av-epic
