### ISSUE TITLE
Chartbeat causes large increase in load event/fully loaded

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#6326] opened 2020-04-27 16:19 UTC
**Describe the bug**
Time to load event and fully loaded shows 30-40% increase since Chartbeat was enabled. See the following graph taken from SpeedCurve (i.e. WebPageTest):

![image](https://user-images.githubusercontent.com/11161809/80395243-d3f3a780-88aa-11ea-98c8-b9700ca7422a.png)

Tests run using:
- Chrome - Ireland
- 5000/1000 Kbps, 28ms Latency

This was raised with the vendor who recommended we use `defer` instead of `async` to mitgate this, giving this example:

```
<script defer="true" type="text/javascript" src="//static.chartbeat.com/js/chartbeat.js" data-react-helmet="true"></script>
```

**Testing notes**
- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment] 2021-08-20 15:07
@jamesdonoh wondering how to recreate this graph in speedcurve?

**Comment by aeroplanejane** [comment] 2021-08-23 15:27
@rebeccamcginn https://app.speedcurve.com/bbc/news-ws/site/?b=chrome&cs=lg&d=365&dc=2&de=1&ds=1&r=eu-west-1&s=317507&u=394955
![Screenshot 2021-08-23 at 16 23 44](https://user-images.githubusercontent.com/22519682/130474212-f560c6ec-e349-4979-85e8-72440d6b2c2f.png)

**Comment by aeroplanejane** [comment] 2021-09-09 11:32
Fix was implemented but hasn't fully resolved the issue. Going to close this ticket as the fix was implemented and we're not going to do further analysis on root cause and potential solutions now our page fully loaded times are on. average. 2.5s and we think that's good enough for now. Thanks for investigating and fixing @rebeccamcginn and @nicola-d-bbc

**Closed as completed by aeroplanejane** 2021-09-09 11:32 UTC
Labels: bug, Good first issue, performance
