### ISSUE TITLE
Simorgh internal links for supported asset types

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#4144] opened 2019-10-07 12:04 UTC
**Is your feature request related to a problem? Please describe.**
Currently the [Simorgh logic that decides if an inline link uses the React Router link](https://github.com/bbc/simorgh/blob/latest/src/app/containers/InlineLink/index.jsx#L18-L33) only supports Article URLs. We need to extend this logic so that it can identify the asset types that Simorgh supports, E.G. Articles, Front pages, MAPs.

We also should consider how this works for cross services linking, especially when some services/asset types won't be routed in production.

**Describe the solution you'd like**
Extend the logic for internal routing to support new asset types per service depending what is available in production. 

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**
We may need to use toggles to have context of which asset type is live in production for which service.

**Comment by dr3** [comment] 2019-10-07 12:07
Duplicate of https://github.com/bbc/simorgh/issues/3869

**Closed as completed** 2019-10-07 12:09 UTC
Labels: Refinement Needed, ws-media, MAP
