### ISSUE TITLE
Toggle Context Provider proptype error

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6196] opened 2020-04-15 17:43 UTC
**Describe the bug**
Proptype console error when running application on localhost

**To Reproduce**
Steps to reproduce the behaviour:

1. `npm install` `npm run dev`
2. Visit any Simorgh page, e.g. `http://localhost:7080/thai`
3. See proptype error in console:

```
Warning: Failed prop type: The prop `origin` is marked as required in `ToggleContextProvider`, but its value is `null`.
    in ToggleContextProvider (created by WithContextsContainer)
    in WithContextsContainer (created by VariantContainer)
    in VariantContainer (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in App (created by Context.Consumer)
    in withRouter(App) (created by ClientApp)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by ClientApp)
    in ClientApp
```

**Expected behaviour**
No proptype error

**Screenshots**
Above.

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Firefox
- Version 76.0

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**
The reason for this is that where ToggleContextProvider is used, the `bbcOrigin` value passed to it is null. https://github.com/bbc/simorgh/blob/latest/src/app/containers/PageHandlers/withContexts.jsx#L29

It would be good to have a default value for this locally, e.g. `www.test.bbc.com`.

**Comment by joshcoventry** [comment] 2021-02-09 17:04
Cannot reproduce locally, closing this.

**Closed as completed by joshcoventry** 2021-02-09 17:04 UTC
Labels: bug, cross-team
