### ISSUE TITLE
Wrong padding for section dividers

### ISSUE THREAD

**Issue by OlgaLyubin** [bbc/simorgh#3889] opened 2019-09-19 10:26 UTC
**Describe the bug**
There are wrong paddings for section dividers (one is 16px and another one is 32px).  It seems that the wrong padding is applied when there is only one story promo in the group.

See the screenshot below:
<img width="767" alt="Screenshot 2019-09-19 at 11 12 43" src="https://user-images.githubusercontent.com/17802955/65235954-7c4cbc80-dacf-11e9-9a4b-357ab62bd405.png">

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a WS front page of e.g. Thai service
2. Scroll down to a section with one story promo in the group
3. See error

**Expected behaviour**
Padding  should be 24 px between divider and item below. See the screenshot below or check Zeplin:

<img width="433" alt="Screenshot 2019-09-19 at 11 16 01" src="https://user-images.githubusercontent.com/17802955/65235933-735beb00-dacf-11e9-8d3c-23b0726b6790.png">

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by DenisHdz** [comment] 2019-09-20 10:50
I think the problem is with the `MarginWrapper` in the `FrontPageSection` container. I believe we can refactor it since the desktop top story was already merged.

**Closed as completed** 2019-09-30 07:35 UTC
