### ISSUE TITLE
Create schema for OJs data

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#532] opened 2018-08-21 08:40 UTC
**Is your feature request related to a problem? Please describe.**
There is no schema for the onward journeys data

**Describe the solution you'd like**
Create one

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by pjlee11** [comment] 2018-09-21 09:18
Closing as a duplicate of https://github.com/bbc/simorgh/issues/526

**Closed as completed by pjlee11** 2018-09-21 09:18 UTC
