### ISSUE TITLE
[STY Post Live] Ensure chartbeat is working correctly on STY assets

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#6697] opened 2020-05-28 13:38 UTC
**Is your feature request related to a problem? Please describe.**
It looks like the chartbeat may not be working correctly on STY assets.

**Describe the solution you'd like**
Ensure chartbeat is loaded and running correctly all STY assets.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [ ] This feature is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment] 2020-05-28 13:55
I believe it should be fixed by adding the following to the `/pages/StoryPage`:
```
import ChartbeatAnalytics from '#containers/ChartbeatAnalytics';
...
<ChartbeatAnalytics data={pageData} />
```

**Comment by lizcameron** [comment] 2020-05-29 08:42
Closed as a duplicate of https://github.com/bbc/simorgh/issues/6689

**Closed as completed by lizcameron** 2020-05-29 08:42 UTC
Labels: Refinement Needed, ws-articles, stories-STYs
