### ISSUE TITLE
Hide player and display error where AV and audio stream is expired 

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#4796] opened 2019-11-25 17:48 UTC
**Is your feature request related to a problem? Please describe.**
Users in CPS can disable a stream so that it is no longer active on a MAP and cannot play content. This is because the channels are shared across services and editorial staff need to ensure they disable a stream where their content is no longer being streamed to a channel. 

We need to stop the media from playing when the stream is tagged as expired. 

**Describe the solution you'd like**
**Scenario: Unavailable Stream** 
Given a live stream has been flagged as expired in CPS
and the Ares response returns available = false
when the page is published 
then the stream will not be played and an error will be displayed stating that the video is unavailable

This MAP has an expired stream: https://test.bbc.com/pidgin/media-23256549
We need to ensure users cannot play the stream. This is the current pal example: https://pal.test.bbc.com/pidgin/media-23256549?_x_candy_override=https%3A%2F%2Fapi.test.bbc.co.uk

For AV, there will be a placeholder image (when provided by Ares) and the message "Sorry we are unable to bring you this content right now".

For Audio, there will be no placeholder image and the message "Sorry we are unable to bring you this content right now".

We will implement the error message and designs here: 
https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5e2b162bafdbbf9579e33625

We will default to English for now until we have translations for all services.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by ryanmccombe** [comment] 2019-11-26 11:59
See error component here: https://github.com/bbc/psammead/pull/2625

**Comment by ryanmccombe** [comment] 2020-01-16 11:26
Design link is here: https://app.zeplin.io/project/5d4d77b1fcbfc79bf47e0294/screen/5de12c359142f96df69d9231

Psammead component: https://github.com/bbc/simorgh/blob/latest/cypress/support/config/services.js

The design is different to the component, but Ed confirmed we're okay to use this component for now as it is already built

**Comment by LilyL0u** [comment] 2020-01-16 15:12
This expired test stream is no longer expired :0 https://www.test.bbc.com/pidgin/media-23256549

Pal one looks like this:

![UNADJUSTEDNONRAW_thumb_95](https://user-images.githubusercontent.com/54575620/72536674-98d8e580-3872-11ea-9f74-4801aed06ee1.jpg)

**Comment by ryanmccombe** [comment] 2020-01-16 16:50
The stream is marked as unavailable within CPS and the API:

![Screen Shot 2020-01-16 at 16 49 15](https://user-images.githubusercontent.com/8601460/72544970-2bcc4c80-3880-11ea-9c28-244b0579327e.png)

The essence of the bug is we're just ignoring that and showing the video anyway - so it just looks like it hasn't expired :)

**Comment by aeroplanejane** [comment] 2020-01-16 16:54
Is the expectation clear here? Should we refine this early next week with Ed? @rebeccarfmcginnbbc @ryanmccombe @LilyL0u

**Comment by ryanmccombe** [comment] 2020-01-16 19:50
We had a 3 amigos on it - the plan is to leave it for now until we get an ally swarm on the existing component (it is marked as alpha)

**Closed as completed** 2020-02-05 13:33 UTC
Labels: Good first issue, ws-media, MAP
