### ISSUE TITLE
Live Radio Charbeat sections values are 'unknown'

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6036] opened 2020-03-31 11:31 UTC
**Describe the bug**
Visit a Live Radio page https://www.bbc.com/amharic/bbc_amharic_radio/liveradio on canonical or on amp https://www.bbc.com/amharic/bbc_amharic_radio/liveradio.amp 

See that the values for sections being sent include 'unknown'. 

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/amharic/bbc_amharic_radio/liveradio
2. Inspect DOM
3. See value of `"Amharic, Amharic - , Amharic - unknown, Amharic - unknown, Amharic - unknown"` within chartbeat's section value.

**Expected behaviour**
To have correct sections for live radio and not `Amharic - unknown`

**Screenshots**
AMP:
<img width="927" alt="Screenshot AMP" src="https://user-images.githubusercontent.com/3028997/78021488-3bb9df80-734b-11ea-952b-2d6c1db22ebc.png">
Canonical:
<img width="955" alt="Screenshot Canonical" src="https://user-images.githubusercontent.com/3028997/78021486-3b214900-734b-11ea-8fa7-40265623af9e.png">

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Chrome
- Version 83.0

**Testing notes**

- [ ] This bug fix is expected to need manual testing.

**Additional context**

**Comment by aeroplanejane** [comment] 2020-03-31 12:09
This isn't a bug, this is intended behaviour - value is also 'unknown' on PAL also and given the absence of a clear indication of which value should replace it we left it as 'unknown' - Chartbeat is geared towards articles and other editorially curated content so live radio pages are a bit of an anomaly and primarily used to understand user behaviour and views of the page.

**Comment by graeme-lindsay** [comment] 2020-04-01 10:14
Closing issue.

**Closed as completed by graeme-lindsay** 2020-04-01 10:14 UTC
Labels: bug, ws-media
