### ISSUE TITLE
Test page showing data from scenarios

### ISSUE THREAD

**Issue by jimjohnsonrollings** [bbc/simorgh#1157] opened 2019-01-11 11:34 UTC
**Describe the bug**
Viewing the source of `/news/articles/c9rpqy7pmypo` on Test I can see `<meta data-react-helmet="true" name="description" content="Meghan follows the royal bridal tradition started by the Queen Mother in 1923."/>`.  This content is only available in the scenario sample json, and not in the json we are receiving from Ares, therefore is not expected to be rendered in the page.

Similarly `<meta data-react-helmet="true" name="twitter:description" content="Meghan follows the royal bridal tradition started by the Queen Mother in 1923."/>` and `<meta data-react-helmet="true" name="description" content="Meghan follows the royal bridal tradition started by the Queen Mother in 1923."/>`

**To Reproduce**

1. Go to an article
2. View source
3. Search for `name="og:description"`
4. See content not available in Ares response

**Expected behavior**
The description is empty, as no data for that field is available from Ares.

**Screenshots**

**Additional context**

- [ ] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by bcmn** [comment] 2019-01-14 12:06
Closing as duplicate of [this issue](https://github.com/bbc/simorgh-infrastructure/issues/194).

**Closed as completed by bcmn** 2019-01-14 12:06 UTC
Labels: bug, Refinement Needed
