### ISSUE TITLE
Apply RTL to `html` tag for RTL services

### ISSUE THREAD

**Issue by dr3** [bbc/simorgh#1557] opened 2019-04-09 14:00 UTC
**Is your feature request related to a problem? Please describe.**
We should apply the `dir="rtl"` or `dir="ltr"` values to our pages. 

**Describe the solution you'd like**
Configure it at a service level and then use helmet to add it to a page using the [logic already in place](https://github.com/bbc/simorgh/blob/latest/src/server/Document/component.jsx#L35). We should insure that navigating between RTL and LTR (news & persian) pages use the direct direction when moving.

This should be done in a way that easily allows it to be used by ws frontpages.

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by sareh** [comment] 2019-04-10 11:48
@dr3 this is a duplicate of https://github.com/bbc/simorgh/issues/611, so if it's okay with you, I'll close this issue.

**Closed as completed** 2019-04-10 11:50 UTC
Labels: Refinement Needed
