### ISSUE TITLE
Audio player clipped when device width is 240px

### ISSUE THREAD

**Issue by jroebu14** [bbc/simorgh#3807] opened 2019-09-17 08:34 UTC
**Describe the bug**
Audio player's controls are clipped when device width is 240px as shown below.

![image (1)](https://user-images.githubusercontent.com/4798332/65025282-5805aa00-d92e-11e9-96be-7c0d485fe5a6.png)

**To Reproduce**

1. Go to https://www.test.bbc.com/korean/bbc_korean_radio/liveradio
2. Set browser width to 240px and observe the player controls being clipped at the bottom.

**Expected behavior**
Audio player should be fully visible. WS supports device widths of 240px and above.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by ibMadbouly** [comment] 2019-10-09 14:01
reproduced this and it looks fine for me based on the following screenshot 
<img width="337" alt="Screen Shot 2019-10-09 at 3 47 34 PM" src="https://user-images.githubusercontent.com/47124571/66488302-ff997680-eaad-11e9-9782-4c9ade191a42.png">

**Comment by paruchurisilpa** [comment] 2019-10-10 08:48
Looks good to me..

**Comment by paruchurisilpa** [comment] 2019-10-10 08:48
This can straight to done as discussed with @ibMadbouly because it's not a PR, there is nothing to be merged..

**Closed as completed** 2020-06-08 15:13 UTC
Labels: bug, ws-media
