### ISSUE TITLE
Investigate Cookie consent banner e2e's

### ISSUE THREAD

**Issue by chris-hinds** [bbc/simorgh#4663] opened 2019-11-14 09:35 UTC
Our e2e's (Cypress tests) are slow, often fail/timeout for no apparent reason and are run multiple times across different page types/services.

One of our problem tests is the consent banner tests. It looks like this test runs against every page type for every service.

We'd like to know;

1) How long does this test take to run for a single page type and a single service
2) How often is this test run? Is run for every page type?
3) Should this test be pulling data from the service config? It checks translation which do not change across page types
4) Can you recommend any changes/enhancements to the current test that might speed it up/reduce the number of times it fails

**Comment by PriyaKR** [comment] 2019-11-20 14:08
It totally takes 15 mins for the cookie tests to run on canonical page types and another 15 mins to run on amp pages locally.But on jenkins it took totally 4 mins for the two cookie(canonical and amp) tests to be run across all pagetypes and all services.

1.  How long does this test take to run for a single page type and a single service - 3 to 4secs
2. How often is this test run? Is run for every page type? - yes for all page types
3. Should this test be pulling data from the service config? It checks translation which do not change across page types - true
4. Can you recommend any changes/enhancements to the current test that might speed it up/reduce the number of times it fails

These are my inferences looking at the cookie tests locally and on CI(cron job) i would say if the cookie behaviour are same across all the services except change in translation we should make it run for news,R to L language, mundo and thai may be.

**Comment by jroebu14** [comment] 2019-11-20 14:16
Makes sense to me

**Comment by andrewscfc** [comment] 2019-11-20 14:22
I worked for a long time on the Orbit cookie banner implementation so hopefully can give some decent insight, as the Simorgh implementation is essentially a duplicate of the Orbit implementation but compatible with Amp etc.

> These are my inferences looking at the cookie tests locally and on CI(cron job) i would say if the cookie behaviour are same across all the services except change in translation we should make it run for news,R to L language, mundo and thai may be.

Yeah I'd say the cookie banner should be tested once for each significantly distinctive visual layout, to my knowledge RTL language and LTR, I imagine those other services may exhibit other visual layouts.

I also suspect the flakiness of the banners may be due to cookies being dropped between runs, for example if `ckns_privacy` cookie is dropped, the cookie banner will display, if not the privacy banner will display (the privacy banner itself drops `ckns_privacy`). This will 'flip-flop' depending on if cypress runs in a clean session with all cookies deleted, I'm not sure if this is the case as I'm not that experienced with cypress.

Hope this helps

**Comment by PriyaKR** [comment] 2019-11-20 15:09
There is this command `cy.clearCookies();` in our tests between each run of cookie test across services which clears the cookie value set.

**Comment by andrewscfc** [comment] 2019-11-20 15:20
> There is this command `cy.clearCookies();` in our tests between each run of cookie test across services which clears the cookie value set.

Okay, that hopefully rules out the 'flip-flopping' between privacy and cookie banner :)

**Comment by andrewscfc** [comment] 2019-11-21 10:16
~~Looks like the 'flip-flopping' issue I was suggesting on a chromatic snapshot: 
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/9645462/69328859-e99fd980-0c47-11ea-8088-36cd59cc5543.png">~~

EDIT: Sorry been here a bit longer now, I now realise this applies to chromatic rather than the E2E tests, please ignore this comment!

**Closed as completed** 2020-09-17 14:56 UTC
Labels: investigation, technical-work
