### ISSUE TITLE
Meta description is empty

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#1138] opened 2019-01-09 10:18 UTC
**Is your feature request related to a problem? Please describe.**
We currently have Lighthouse tests erroring with this:
```
Document does not have a meta description
Description text is empty.
```
This is the case on the Test & Live environments, until the Optimo team provide a Promo Summary string. (https://www.test.bbc.com/news/articles/c85pqyj5m2ko) & (https://simorgh.api.bbci.co.uk/news/articles/c85pqyj5m2ko)

**Describe the solution you'd like**
Optimo need to pass the promo.summary value to Ares, so that the Simorgh application can render it in this tag: `<meta name="description" content="....." >`

**Describe alternatives you've considered**
N/A

**Testing notes**
[Tester to complete]

Dev insight: Lighthouse test should no longer error on Test and Live environments. 

**Additional context**

- [x] Initially labelled with ["Refinement needed"](https://github.com/BBC-News/simorgh/labels/Refinement%20Needed)

**Comment by bcmn** [comment] 2019-01-09 12:37
Is this a duplicate of #842?

**Comment by bcmn** [comment] 2019-01-09 13:01
Closing as duplicate.

**Closed as completed by bcmn** 2019-01-09 13:01 UTC
Labels: Refinement Needed, external blocked
