### ISSUE TITLE
Investigate font CSP errors on some Story pages

### ISSUE THREAD

**Issue by andrewscfc** [bbc/simorgh#6611] opened 2020-05-21 15:49 UTC
**Describe the bug**
When you load some Story pages when you open the console you see many failed attempts to load fonts:
<img width="1246" alt="image" src="https://user-images.githubusercontent.com/9645462/82577088-61f94000-9b82-11ea-8773-e381a16237ba.png">

https://www.test.bbc.com/gahuza/49116789?renderer_env=live

Multiple examples were found when we tested includes:
https://www.test.bbc.com/gahuza/amakuru-50330144?renderer_env=live
https://www.test.bbc.com/gahuza/amakuru-50332056?renderer_env=live

**To Reproduce**
Steps to reproduce the behaviour:

1. Visit one of the urls listed above
1. Open console
Observe font download errors

No obvious visual problem can be seen on the page.

**Expected behaviour**
No font download errors

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac
- Browser Firefox and Chrome tested, could be more widespread

**Testing notes**

- [X] This bug fix is expected to need manual testing.

**Additional context**
- Reach out @sareh for more context on the issue. (There was a long thread in Slack).
- Some pages do not seem to exhibit the problem: https://www.test.bbc.com/gahuza/amakuru-36544625?renderer_env=live 

It was found during includes testing so could be related to includes.

**Comment by HarveyPeachey** [comment] 2020-05-26 12:52
~Just to point out, I've also found an issue with fonts using the `data:` prefix but it seems to be only showing on normal chrome for me:~

<img width="1401" alt="Screenshot 2020-05-26 at 13 46 43" src="https://user-images.githubusercontent.com/4706195/82902648-b07a5600-9f57-11ea-910a-1cce7eca3d4b.png">

~But in incognito, I get these:~
<img width="1429" alt="Screenshot 2020-05-26 at 13 50 34" src="https://user-images.githubusercontent.com/4706195/82902784-e586a880-9f57-11ea-9b48-756a2f4b6102.png">

~This was using this test [asset](https://www.test.bbc.com/gahuza/49116789?renderer_env=live), but I am experiencing it on other include assets.~

This was due to a bug with the Grammarly extension so ignore.

**Comment by FK78** [comment] 2020-05-28 14:14
# CSP Fonts Investigation

## The Problem

We are seeing CSP Font errors on **some** STY pages, these errors don't seem to be impacting the page in any way, but nonetheless should be fixed.

From our investigation we have discovered that these errors are caused by some Includes, this is because the Includes are requesting fonts from whatever domain the code is being hosted on which originally is from smallprox, the convention used to obtain the fonts is `src: url(/static/media/BBCReithSans_W_Md.woff2)`. On localhost it would append `http://localhost:7080` to the URL and attempt to grab the fonts as the font URL's are using a relative path.

**Note:** The `data:` error mentioned by @HarveyPeachey was caused by the browser extension `Grammarly` so is a non issue.

## A possible solution

The IDT team could set the base URL depending on which fonts we need for the Include, e.g. `https://gel.files.bbci.co.uk` for Reith fonts and `https://ws-downloads.files.bbci.co.uk/fonts` for all other fonts.

### Includes used in the investigation:

- /idt2/41a6ad82-8bad-482e-9645-301af4a8e857/html

**Comment by andrewscfc** [comment] 2020-05-28 14:28
Thanks for the investigation @FK78, do you know why this isn't a problem on our PAL pages? May be a question for VJ team to, have you spoken with ~@eagerterrier~ @Tarqwyn the include above is IDT ?

**Comment by sareh** [comment] 2020-05-28 14:39
We don't have Content Security Policy headers set on the PAL. 

The same <style> tag with the fonts here in the Simorgh page https://www.bbc.com/gahuza/49116789 are in the PAL page, but there are no network requests for them.
```
...
@font-face {
    font-family: 'Padauk';
    font-display: swap;
    src: url(/static/media/PadaukBold.ttf) format("truetype");
    font-weight: bold;
  }
...
```

**Comment by HarveyPeachey** [comment] 2020-06-02 08:57
Blocked externally pending a fix from the Smallprox team Jira - CPSROADMAP-10200.

Edit: Last update on PRB-1341, detail about current blockers for this work is being discussed.

**Comment by joshcoventry** [comment] 2020-07-10 11:11
@HarveyPeachey Has there been any update on this?

**Comment by HarveyPeachey** [comment] 2020-07-10 11:15
> @HarveyPeachey Has there been any update on this?

@joshcoventry Yep last comment was a week ago on PRB-1341 was that more detail was being gathered about work that is blocking a fix for this from @Tarqwyn.

**Closed as completed** 2020-10-28 10:56 UTC
Labels: bug, ws-articles, includes
