### ISSUE TITLE
Error in video object on TC2 MAP assets

### ISSUE THREAD

**Issue by aeroplanejane** [bbc/simorgh#6388] opened 2020-05-04 11:08 UTC
Use the Structured data testing tool with the following URLs https://search.google.com/structured-data/testing-tool

https://www.test.bbc.com/mundo/noticias/2016/04/160427_tc2_testmap1
https://www.bbc.com/bengali/multimedia/2016/08/160801_baghdad_rashid_street_100yrs_video

Note the error in video object on TC2 MAP assets

![Screenshot 2020-05-04 at 12 11 19](https://user-images.githubusercontent.com/22519682/80960256-6e4e7080-8e00-11ea-9ebe-b0c8be0e828a.png)

Expected behaviour: 
No errors in the video or audio object in the schema

**Comment by gavinspence** [comment] 2020-07-27 16:12
Duplicate of [5777]( https://github.com/bbc/simorgh/issues/5777)

**Closed as completed by gavinspence** 2020-07-27 16:12 UTC
Labels: bug, low-priority, ws-media
