### ISSUE TITLE
Cypress CYPRESS_UK env variable does not work locally

### ISSUE THREAD

**Issue by 12** [bbc/simorgh#2916] opened 2019-08-06 13:12 UTC
**Describe the bug**
Currently when applying the `CYPRESS_UK=false` flag and running Cypress tests against `LIVE` using `CYPRESS_APP_ENV=live` (as per https://github.com/bbc/simorgh#tests), tests for World Service sites fail, or don't run in some cases. This is because `news` redirects to `.co.uk` (when inside UK territory), but all WS sites redirect to `.com`, regardless of location. Cypress cannot run tests across two domains.

**To Reproduce**

1. `cd simorgh`
2. Checkout `persian-e2e-asset` branch
3. `CYPRESS_APP_ENV=live CYPRESS_UK=false npm run cypress`
4. Run `articleBodySpec`
5. See spec not run

**Expected behavior**
All test spec's run

**Additional context**
This will probably not affect e2e runs that happen outside the UK (i.e. external contributors, or CI builds), but does affect those who run the tests inside the UK.

**Comment by jamesbrumpton** [comment] 2019-08-06 14:06
This is currently blocking us from testing/implementing https://github.com/bbc/simorgh/pull/2907 . It will also prevent us from testing/implementing articles for the other APUP services too as they all point to `bbc.com/` . 

When running the tests on using Cypress' `interactive` mode the browser attempts to run on `.com` but redirects to `.co.uk` . Given that `/persian` only works via `.com` the tests never run but also don't fail, which gives us a false positive, therefore the tests look as though they pass.

**Comment by jamesbhobbs** [comment] 2019-08-20 20:19
Dupe of https://github.com/bbc/simorgh/issues/2123

**Closed as completed by jamesbhobbs** 2019-08-20 20:19 UTC
Labels: bug, cypress
