### ISSUE TITLE
Fix React warnings: `undefined` in src/app/containers/ArticleTimestamp/index.test.jsx

### ISSUE THREAD

**Issue by thekp** [bbc/simorgh#3110] opened 2019-08-13 11:13 UTC
Describe the bug
There are React warnings in unit tests.

To Reproduce

Go to simorgh in terminal
Run npm run test:unit
Observe React warnings:
```
    console.log src/testHelpers/setupTests.js:19
      Test failed because too many React warnings were detected. Please fix the following:
      Warning: Failed prop type: The prop `firstPublished` is marked as required in `ArticleTimestamp`, but its value is `undefined`.
          in ArticleTimestamp
    console.error src/testHelpers/setupTests.js:30
      Warning: Failed prop type: The prop `firstPublished` is marked as required in `ArticleTimestamp`, but its value is `undefined`.
          in ArticleTimestamp
    console.error src/testHelpers/setupTests.js:30
      Warning: Failed prop type: The prop `lastPublished` is marked as required in `ArticleTimestamp`, but its value is `undefined`.
          in ArticleTimestamp
    console.log src/testHelpers/setupTests.js:19
```
Expected behaviour

No React warning for test suite.

Testing notes

No testing required.

**Comment by hotinglok** [comment] 2019-08-20 15:19
Duplicate of #3292

**Closed as completed by hotinglok** 2019-08-20 15:19 UTC
Labels: bug
