### ISSUE TITLE
E2E tests for On Demand Radio pages

### ISSUE THREAD

**Issue by LilyL0u** [bbc/simorgh#6510] opened 2020-05-13 15:21 UTC
New page type for tests
Can test viewport to see if hero image appears when it should, and does not appear when it shouldn't. (cy.viewport)

Do we want to test this beginning from the front page with a schedule, to click on the newest episode so it is never expired? We have done a similar journey with the script switcher tests: clicking on a page from the front page - but this still starts from a page of the page type tested (MAP), rather than starting from the front page.

**Comment by karinathomasbbc** [comment] 2020-05-14 08:35
Another alternative is to write something which queries the radio schedule endpoint for that service. It's just that some pages don't have the schedule on the front page yet

**Comment by karinathomasbbc** [comment] 2020-05-14 09:56
Closing as a duplicate of #6245

**Closed as completed by karinathomasbbc** 2020-05-14 09:56 UTC
