### ISSUE TITLE
Remove Local JSON Path & Assets from Simorgh Prod

### ISSUE THREAD

**Issue by jamesbrumpton** [bbc/simorgh#1327] opened 2019-02-20 17:25 UTC
**Describe the solution you'd like**
Currently, we do not remove the local data path or assets from Simorgh when building for test or live.

A simple, short-term solution may be to leave the express path logic in when bundling to RPM, but not include any of the JSON files.

**Testing notes**
Cypress tests will not regress and work as expected. Tests should still run locally.

- [x] Initially labelled with ["Refinement needed"](https://github.com/bbc/simorgh/labels/Refinement%20Needed)

**Comment by dr3** [comment] 2019-02-20 17:26
Possible duplicate of https://github.com/bbc/simorgh/issues/1235, not the same implementation but same end goal

**Comment by bcmn** [comment] 2019-02-20 18:29
I think it'd be worth evaluating as part of the refinement with James whether this solution proves quicker, even if only a short-term option.

**Closed as completed** 2019-06-12 17:54 UTC
Labels: Refinement Needed
