### ISSUE TITLE
Update skip link translations for Recommendations

### ISSUE THREAD

**Issue by JonBeeb** [bbc/simorgh#7381] opened 2020-08-03 12:26 UTC
**Is your feature request related to a problem? Please describe.**
Part of https://github.com/bbc/simorgh/issues/6267 involved adding skip links to the CpsRecommendations and the link texts used were defaulted to placeholder texts in English until we had translations for services that support recommendations. 

We now need to update these translations as they are now available. 

**Describe the solution you'd like**
Update the service config with translations for the following services that use Recommendations:

| Service  | Translations for: "Skip [title of component] and continue reading" | Translations for: "End of [title of component]" |
| ------------- | ------------- | ------------- |
| Arabic  |  تخطى [title of component] وواصل القراءة  | [title of component] نهاية |
| Hindi | छोड़कर [title of component] आगे बढ़ें| समाप्त|
| Mundo | Saltar [title of component] y continuar leyendo  | Final de [title of component]|
| Portuguese | Pule [title of component] e continue lendo | Fim do [Title of component]  |
| Turkish  | Haberin başlığını atlayın ve okumaya devam edin | Haberin sonu|

**Describe alternatives you've considered**

**Testing notes**
[Tester to complete]
- updated snapshots / unit  test to have updated translations

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**

**Comment by rhenshaw56** [comment] 2020-08-04 08:31
@JonBeeb is this a duplicate of #6267 ? the only thing that hasn't been added is the missing translations as most of the functionality a11y requirement's been met in #6267

**Comment by JonBeeb** [comment] 2020-08-04 09:25
Yes, 6267 had been closed so this is a duplicate with the missing translations (all except Portuguese)

**Closed as completed** 2020-08-05 13:28 UTC
Labels: Refinement Needed, ws-articles, stories-STYs, Recommendations
