### ISSUE TITLE
Burmese Top Stories layout on live is overlapping 

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#6085] opened 2020-04-03 08:33 UTC
**Describe the bug**

On the Burmese front page, for breakpoints 1008px+ (desktop layout) if there is a Headline that is long and doesn't have a space, it stretches out the image as well, leading to this overlap.

<img width="1147" alt="Screenshot 2020-04-03 at 09 31 42" src="https://user-images.githubusercontent.com/3028997/78340469-123cc600-758e-11ea-9e7c-f7eacfc1df2c.png">

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to https://www.bbc.com/burmese.amp or https://www.bbc.com/burmese in Firefox on a device that is greater than 1008px wide
2. Scroll down to Top Stories row 2
4. See overlapping story promos

**Expected behaviour**
No overlapping.

**Screenshots**

**Desktop (please complete the following information):**

- OS: Mac OS
- Browser Firefox nightly Version 76.0a1 & Firefox v74

Can not replicate in Chrome or Safari.

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**

**Comment by sareh** [comment] 2020-04-03 08:38
This issue is to do with the Story Promo heading not having any spaces.

**Comment by sareh** [comment] 2020-04-03 08:50
This issue will be happening on all instances of story promo where such a long headline is used, e.g. `နှာခေါင်းစည်းတပ်သင့်မတပ်သင့်ပညာရှင်တွေပြန်သုံးသပ်`, not just in Top Stories.

**Comment by Bopchy** [comment] 2020-04-06 15:50
This appears to be caused by the Grid not being respected on Firefox, when there are long headlines present. I logged this as an issue via webcompat - https://github.com/webcompat/web-bugs/issues/51224 , as it the image being stretched out by the long headline text seems to be happening in Firefox only

EDIT: Above mentioned issue has been closed as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1530097. Issue can still be seen on local.

**Comment by Bopchy** [comment] 2020-04-07 09:31
Adding an `externally blocked` label to this, as the issue is being handled by Firefox.

**Comment by joshcoventry** [comment] 2020-07-10 11:03
Issue still not fixed by Firefox, we can fix on our side.

A fix has already been done on the Story pages (https://github.com/bbc/simorgh/pull/7170), the same needs to be applied to Top stories. @Simon2828 you may want to look into this one too.

**Closed as completed** 2020-08-14 10:52 UTC
Labels: bug, low-priority, ws-articles
