### ISSUE TITLE
Opera Mini Extreme mode layout bugs - StoryPromos on Front page & Related on CPS assets

### ISSUE THREAD

**Issue by sareh** [bbc/simorgh#5684] opened 2020-02-26 11:44 UTC
**Describe the bug**
On Opera Mini - only when on Extreme mode, we get this layout, with images for story promos not being aligned.
<img src="https://user-images.githubusercontent.com/3028997/75342080-9adc8e00-588d-11ea-9173-3dd0acf5999a.jpg" alt="extreme mode" width="200px" />

It looks like this when in standard mode (not 'extreme'), which is what we want
<img src="https://user-images.githubusercontent.com/3028997/75342078-99ab6100-588d-11ea-8e85-3651b3f9946a.jpg" alt="normal mode" width="200px" />

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to `www.bbc.com/thai` on an Opera Mini browser
2. Turn on Extreme mode
3. See layout with different widths for story promos - it looks broken

**This only occurs on the extreme mode. On the normal mode, it's just fine**

**Expected behaviour**
Layout to look similar to that as on the standard 'automatic' mode:

It looks like this when in automatic mode (not 'extreme'), which is what we want
<img src="https://user-images.githubusercontent.com/3028997/75342078-99ab6100-588d-11ea-8e85-3651b3f9946a.jpg" alt="normal mode" width="200px" />

**Screenshots**

**Smartphone (please complete the following information):**

- Device: One Plus 7 Pro
- OS: Android OS 11
- Browser Opera Mini

**Testing notes**

- [x] This bug fix is expected to need manual testing.

**Additional context**
This is a message from someone who used to work for Opera mini:

These instructions should still work: https://dev.opera.com/articles/installing-opera-mini-on-your-computer/
However, you won't be able to really inspect the page source since Opera Mini is a Presto-powered black box: there's no DOM or CSS that can be inspected, as all of it lives on the server side, in an instance of the Presto engine.
So, a better option might be to try to download Opera 12.1* (Presto) and see if you can reproduce the issue.  http://ftp.opera.com/ftp/pub/opera/win/

If you have more questions, I suggest reaching out to `twitter accounts @janstandal or @erikjmoller`

**Comment by DenisHdz** [comment] 2020-04-20 13:17
I've been investigating this and I believe the bug is due to the way we calculate the fallbacks widths in the `psammead-grid`.

For example, if I apply a width of `296px` directly to the `StoryPromoLi` in Simorgh, which is the result of this calculation `calc(6/6*(100% - 6 * 0.5rem) + 5 * 0.5rem );`, the layout is displayed correctly. 

**Before:**
![before](https://user-images.githubusercontent.com/46446236/79755793-907cc480-8311-11ea-8f91-ef516243600c.jpg)

**After:**
![after](https://user-images.githubusercontent.com/46446236/79756164-1d278280-8312-11ea-9c67-7496dadbd952.jpg)

The method `calc()` is supposed to not be compatible with Opera Mini https://caniuse.com/#feat=calc, however, if we disable the Extreme Mode, the layout is rendered correctly, which makes me think that the Extreme Mode doesn't know how to handle properly the calculations.

**Comment by EinsteinNjoroge** [comment] 2020-05-12 08:43
> I've been investigating this and I believe the bug is due to the way we calculate the fallbacks widths in the `psammead-grid`.
> 
> For example, if I apply a width of `296px` directly to the `StoryPromoLi` in Simorgh, which is the result of this calculation `calc(6/6*(100% - 6 * 0.5rem) + 5 * 0.5rem );`, the layout is displayed correctly.
> 
> **Before:**
> ![before](https://user-images.githubusercontent.com/46446236/79755793-907cc480-8311-11ea-8f91-ef516243600c.jpg)
> 
> **After:**
> ![after](https://user-images.githubusercontent.com/46446236/79756164-1d278280-8312-11ea-9c67-7496dadbd952.jpg)
> 
> The method `calc()` is supposed to not be compatible with Opera Mini https://caniuse.com/#feat=calc, however, if we disable the Extreme Mode, the layout is rendered correctly, which makes me think that the Extreme Mode doesn't know how to handle properly the calculations.

I've reproduced this issue in chrome by turning off the grid and lowering my network bandwidth to slow 3G. This explains why the issue only appears in extreme mode.
Given that chrome fully supports `calc`, I don’t think the width calculation is the issue.
![Screen Shot 2020-05-12 at 11 44 40 AM](https://user-images.githubusercontent.com/21374761/81662276-00302c00-9446-11ea-94aa-59a9af3e9a46.png)

**Comment by aeroplanejane** [comment] 2021-02-10 08:39
Won't fix. closing.

**Closed as completed by aeroplanejane** 2021-02-10 08:39 UTC
Labels: bug
