### ISSUE TITLE
Add description, OG and Twitter metadata to PGLs

### ISSUE THREAD

**Issue by simonsinclair** [bbc/simorgh#5158] opened 2020-01-15 11:08 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Ensure PGLs contain the following metadata.

The metadata logic can be found in the metadata [container](https://github.com/bbc/simorgh/blob/latest/src/app/containers/Metadata/index.jsx). And the container is used in the [CpsAssetPageMain](https://github.com/bbc/simorgh/blob/latest/src/app/containers/CpsAssetPageMain/index.jsx#L57) to produce the metadata for that asset.

We need to ensure that other page types like MAP pages can make use of the metadata that is being added for PGL pages and if not we limit it per page asset type. Speak to the Media team to check this.

Generic:
- [x] description = Promo summary - Check with the Media team to see if the current is okay https://github.com/bbc/simorgh/blob/887963dd6cdc1242f43ca0eab5a1167f3f04d11e/src/app/containers/CpsAssetPageMain/index.jsx#L28

Open Graph (Facebook):
- [x] og:title =	Promo Headline Headline
- [x] og:type =	article	[unchanged from article data]
- [x] og:description =	Promo summary 
- [x] og:site_name =	Service name	[unchanged from article data]
- [x] og:locale =	Service locale	[unchanged from article data]
- [x] og:url =	Canonical URL of article	[unchanged from article data]
- [x] og:image = Promo -> IndexImage (same as promo image used on FP ).  If it doesn't exist, use Service -> Logo
- [x] og:image:alt = Promo -> IndexImage -> AltText. If it doesn't exist, use the Service -> Logo -> AltText
- [x] article:author = should be article author [from service config](https://github.com/bbc/simorgh/search?p=2&q=articleAuthor%3A+%27&unscoped_q=articleAuthor%3A+%27) e.g `https://www.facebook.com/bbcnews`

Twitter:
- [x] twitter:creator = Service name e.g. `@BBCMundo` [unchanged from article data]
- [x] twitter:site = Service name e.g. `@BBCMundo` [unchanged from article data]
- [x] twitter:title =	Promo Headline Headline
- [x] twitter:description =	Promo Summary
- [x] twitter:img:src = Promo -> IndexImage (same as promo image used on FP ).  If it doesn't exist, use Service -> Logo
- [x] twitter:image:alt = Promo -> IndexImage -> AltText. If it doesn't exist, use the Service -> Logo -> AltText

**Describe alternatives you've considered**

**Testing notes**
Check if all other metadata that is present is the same as our current articles pages. -- Have checked this and added the metadata that is present on the live article in comments below.

https://developers.facebook.com/tools/debug/ -  Validator for Facebook metadata
https://cards-dev.twitter.com/validator - Validator for Twitter metadata
These tools might only work with live URL's and not with code snippets. So more investigation might need to be done to find other methods of validation of these two instances of metadata.

Existing snapshots will need updating or adding when the correct metadata has been added to the asset data.

Check if there any existing and relevant e2e's and if they need to be updated/removed.

Dev insight: Will Cypress tests be required or are unit tests sufficient? Will there be any potential regression? etc

- [x] This feature is expected to need manual testing.

**Additional context**
- A reference to similar work: https://github.com/bbc/simorgh/pull/5075

**Comment by oluoluoxenfree** [comment] 2020-01-15 16:27
og:title - in the html, not the correct value (`promo.headlines.headline`)
og:type - in the html, not the correct value ('website', hardcoded in CpsAssetMain) Check with Liz that this isn't a mistake between LinkedData and OG.
og:description - in the html, correct!
og:site_name - in the html, correct!
og:locale - in the html, correct!
og:url - in the html, correct!
og:image - in the html, incorrect (we want this image to be the first image in the PGL) ask liz
og:image:alt - incorrect, in html
article:author - not in html, double check with Liz
twitter:creator - in html, should be Twitter handle for that service (done from context). Double check with Liz
twitter:site - in html, should be Twitter handle for that service (done from context).
twitter:title - in html, using full headline, should be short (same as og)
twitter:description - in html, correct
twitter:image:src - in html, incorrect (we want to use an image from PGL). ask liz

**Comment by andrewscfc** [comment] 2020-01-16 11:20
> Requirements from refinement:
`og:title` - `promo.headlines.headline` can be used rather `promo.headlines.shortheadline`
`og:type` - should be `article`, may change MAP pages to `article` too from `website`?
`og:description` - ok
`og:description` - in the html, correct!
`og:site_name` - in the html, correct!
`og:locale` - in the html, correct!
`og:url` - in the html, correct!
`og:image` - as MAP pages, use service logo
`og:image:alt` - as MAP pages
`article:author` - hardcoded `https://www.facebook.com/bbcnews`
`twitter:creator` - `@ ServiceName` e.g. @ BBCMundo
`twitter:site` `@ ServiceName` e.g. @ BBCMundo
`twitter:title` - `promo.headlines.headline` can be used rather `promo.headlines.shortheadline`
`twitter:description` - ok
`twitter:image:src` - as MAP pages, use service logo

*Edit:*
Updated description to reflect discussions in refinement, we still have one outstanding question with @lizcameron: should `og:type` be `article`, on MAP pages as well as on PGL pages.

**Comment by 12** [comment] 2020-01-16 11:23
`article:author` is currently being set here in the `ArticleMetadata` container:

https://github.com/bbc/simorgh/blob/560f096358595ee35c08279c0cc94ec9b2ebd69c/src/app/containers/ArticleMetadata/index.jsx#L23-L35

Where `author` is being defined in `ArticleMain` from the `ServiceContext`

https://github.com/bbc/simorgh/blob/560f096358595ee35c08279c0cc94ec9b2ebd69c/src/app/containers/ArticleMain/index.jsx#L38-L40

As `ArticleMetadata` acts as a wrapper around the `Metadata` container, I suggest we can just move this attribute to the main `Metadata` component.

That, or we create a new `PGLMetadata` container that acts the same as the above.

**Comment by andrewscfc** [comment] 2020-01-16 13:51
We had a swarm looking validators to check our implementation:
> https://developers.facebook.com/tools/debug/ - Validator for Facebook metadata
https://cards-dev.twitter.com/validator - Validator for Twitter metadata
These tools might only work with live URL's and not with code snippets. So more investigation might need to be done to find other methods of validation of these two instances of metadata.

We came up with two options
- Host serverside rendered html on S3 and use only online validators to hit the bucket to preview our metadata being rendered
- Wait to test until mozart routes for PGL page have been created, we can deploy a branch a to test and _potentially_ whitelist the PGL route to not require a cert

**Comment by andrewscfc** [comment] 2020-01-16 14:01
Existing E2E tests:
- cypress/integration/pages/articles/tests.js L34
- cypress/integration/pages/errorPage404/tests.js L87
- cypress/integration/pages/mediaAssetPage/tests.js - L56
- cypress/integration/pages/testsForAllPages.js - L78

**Comment by andrewscfc** [comment] 2020-01-16 15:57
Blocked on completion of https://github.com/bbc/simorgh/pull/5166

**Comment by aeroplanejane** [comment] 2020-01-17 10:44
@andrewscfc Spoke to @lizcameron about this issue earlier. MAPs (media asset pages) have inherited to the og graph metadata from articles, so if you're looking at the implementation for PGLs and STYs we're quite happy if this applies to our MAP pages too (if that makes things easier for you). We don't think the requirements will deviate too much across these page types.  A MAP is effectively article with media on it.

**Comment by lizcameron** [comment] 2020-01-17 11:57
Confirmed: `og:type` should be `article`

MAPs haven't done any og or Twitter metadata work yet, which is why their type is still `website` - this will be changed in future. See https://github.com/bbc/simorgh/milestone/63

**Comment by FK78** [comment] 2020-01-22 15:44
@lizcameron have you got a list of the twitterCreator and twitterSite for each of the services? At the moment it is hardcoded to '@BBCNews' for all services.

**Comment by andrewscfc** [comment] 2020-01-22 17:02
Looks like the PR for this issue is nearly done: https://github.com/bbc/simorgh/issues/4753 

Other than `og:image` and `og:image:alt`, it appears https://github.com/bbc/simorgh/pull/5220 will implement all the requirments in the description.

I have blocked this issue until https://github.com/bbc/simorgh/pull/5220 is merged.

(FYI me and @FK78 began implementing a draft PR before we saw the progress of the media team: https://github.com/bbc/simorgh/pull/5235 )

**Comment by lizcameron** [comment] 2020-01-22 17:29
@FK78 the twitterCreator & twitterSite should match whatever’s on the existing article page for each service - sometimes it's the twitter handle for BBC News, sometimes it's service-specific

**Comment by jimjohnsonrollings** [comment] 2020-01-23 09:32
Similarly to the twitter details, `article:author` should be taken from the relevant service config.

**Comment by rhenshaw56** [comment] 2020-01-23 11:09
blocked pending https://github.com/bbc/simorgh/pull/5220

**Comment by andrewscfc** [comment] 2020-01-23 17:15
Point to consider once https://github.com/bbc/simorgh/pull/5220 is merged: https://github.com/bbc/simorgh/pull/5220#discussion_r370245781

**Comment by paruchurisilpa** [comment] 2020-01-28 15:12
Checked the metadata present on live article and adding it here :

Article URL : https://www.bbc.co.uk/news/articles/cj7xrxz0e8zo

**Og (Facebook) :**
name="og:title" content="This is the headline of this test article - BBC News"/>
name="og:type" content="article"/>
name="og:description" content="This is the headline of this test article"/>
name="og:site_name" content="BBC News"/>
name="og:locale" content="en_GB"/
name="og:url" content="https://www.bbc.com/news/articles/cj7xrxz0e8zo"/>
name="og:image" content="https://www.bbc.co.uk/news/special/2015/newsspec_10857/bbc_news_logo.png"/>
name="og:image:alt" content="BBC News"/>
name="article:author" content="https://www.facebook.com/bbcnews"/

**Twitter:**
name="twitter:creator" content="@BBCNews"/>
name="twitter:site" content="@BBCNews"/>
name="twitter:title" content="This is the headline of this test article - BBC News"/>
name="twitter:description" content="This is the headline of this test article"/>
twitter:img:src —> Cannot be found
name="twitter:image:alt" content="BBC News"/>

**Comment by 12** [comment] 2020-01-29 11:25
Unblocked as #5220 has been merged.

**Comment by 12** [comment] 2020-01-29 11:55
Tested this again, removed the `promo.indexImage` object from the fixture data and it defaults to the service image and image alt as expected.

**Comment by 12** [comment] 2020-01-29 15:59
#5305 was created and has fixed an issue that rendered all Facebook Open Graph metadata incorrect.

**Closed as completed** 2020-02-03 17:03 UTC
Labels: ws-articles, ws-media
