### ISSUE TITLE
Reith font not loading on noJS AMP pages

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/simorgh#1009] opened 2018-11-27 15:01 UTC
BLOCKED ON https://github.com/bbc/simorgh/issues/1178

**Describe the bug**
Possibly related to #1169 and #1053.

When visiting an AMP page with JS disabled, the Reith fonts aren't applied to any of the text in the page (Headline, paragraphs etc).

**To Reproduce**

1. Go to 'http://localhost:7080/news/articles/c85pqyj5m2ko.amp'
2. Disable JS
3. Disable cache
4. Refresh page
5. Observe - no Reith font displayed on the page

Oddly, the Reith font files themselves **are downloaded** - they're just not applied to any of the text. When inspecting an element, the Reith font appears in the `font-family` declaration. Needs investigation.

**Expected behavior**
Reith fonts should load and display on screen

**Additional context**
Whilst something of an edge-case - AMP as a platform is JS-based, so supporting noJS is always going to be tricky - this may become important when we start supporting World Service articles. Some services have a population who use feature phones which may get the AMP version but no JavaScript (e.g. some versions of Opera Mini).

- [x] Initially labelled with ["bug"](https://github.com/BBC-News/simorgh/labels/bug)

**Comment by ryanmccombe** [comment] 2019-06-14 11:07
Can't reproduce this specifically, but there is a wider issue where the Reith font doesn't always get used, independant of whether JS is disabled or Amp is used

Seems to be some race condition - if you clear cache and hard reload a Simorgh article, it will eventually (within 5-10 attempts) load without using the Reith font:

![Screen Shot 2019-06-14 at 12 06 07](https://user-images.githubusercontent.com/8601460/59505245-d3257300-8e9c-11e9-9e6e-99271cc49858.png)

Even though Amp with JS disabled does seem to behave the same way in terms of fonts, the images don't seem to work, and the cookie warning appears without being dismissible:

![Screen Shot 2019-06-14 at 12 07 32](https://user-images.githubusercontent.com/8601460/59505314-0536d500-8e9d-11e9-8655-f74add0668f2.png)

**Comment by ryanmccombe** [comment] 2019-06-14 14:30
Looking at the Reith font intermittently not loading issue, and tracked it down to every @font-face declaration in Psammead having a `font-display` property set to `optional`

This means that, if the font isn't available within a short period of time (vendor-dependent, but reportedly around 100ms) the browser will use the default font, and will not swap it out once Reith downloads

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display

Setting `font-display` to any of the other options will alleviate this, but may cause a longer block period (no visible text) or will cause the font to swap to Reith when it is already visible, which might be jarring

The existing behaviour may be preferred, even if it does mean the site might not use Reith on a user's first visit - welcome any feedback on this

**Comment by jamesbhobbs** [comment] 2019-06-14 14:38
@ryanmccombe definitely want to keep this setting, happy to close this issue on this basis.

**Closed as completed** 2019-06-14 15:30 UTC
Labels: bug, AMP, ws-articles
