### ISSUE TITLE
Investigate live and on-demand playback using new sounds style player

### ISSUE THREAD

**Issue by pjlee11** [bbc/simorgh#2270] opened 2019-07-03 14:03 UTC
**Is your feature request related to a problem? Please describe.**
We want to investigate if we can use the new Sounds audio player version of SMP. 
http://cookbook.tools.bbc.co.uk/audiouiod
http://cookbook.tools.bbc.co.uk/audiouilive

Things to check during the investigation:
  - Internationalisation (translation support both on-screen and off, numbers and letters)
  - RTL support
  - Accessibility (EG: tab order, aria labels etc)

This is related to and potentially blocked by #2151

**Describe the solution you'd like**
Ideal outcome is a list of requirements we need to feedback/follow up on for the new Sounds audio player. 

**Describe alternatives you've considered**
N/A

**Testing notes**
This is an investigation so doesn't require testing

**Additional context**

**Comment by neildoughty** [comment] 2019-07-03 15:32
Other questions. Can we make it news red easily? If we can’t, do we care if it’s branded orange (i don’t think i do).
Does the media play on the index in the player? Do we want to promo to pages, or play the content itself? (Latter would be exciting).
If the content plays in the index, can the player be sticky across multiple Simorgh pages?

**Comment by dr3** [comment] 2019-07-03 15:52
>Can we make it news red easily? 

Yep, i wont link it on github but `Audio UI On Demand` in the SMP cookbook allows for easy changing background and foreground colours as an example :)

**Comment by neildoughty** [comment] 2019-07-03 16:01
Thanks Drew. That feels like one of those ‘early wins’ which Alex W talks about sometimes. A think which may be minor to us (and in some ways users...) but would be excellent for stakeholders. Glad to know it’s achievable.

**Comment by dr3** [comment] 2019-07-03 16:06
> Does the media play on the index in the player? Do we want to promo to pages, or play the content itself?

Do you mean, having the player directly on the index pages? That would be relatively easy actually, we already have all the info in the ares feed (i think), and the SMP work from articles will port nicely, assuming all is well with localisation etc

>If the content plays in the index, can the player be sticky across multiple Simorgh pages?

Yeah thats certainly possible :D

**Comment by pjlee11** [comment] 2019-07-04 13:46
Echoing Drew, there is scope for having the player embedded on any page type, which for things like bulletins and BBC minute is useful on indexes/stories rather than a link. Also as a SPA we should be able to maintain a sticky player across pages and not break the playback during loading states of different pages, :pipe-dream:

**Comment by neildoughty** [comment] 2019-07-04 13:50
excellent. thanks both.

**Comment by jroebu14** [comment] 2019-07-23 12:44
**Internationalisation**

The audio player can be translated and has been for the domestic languages (Welsh, Scottish & Irish). In order for other languages to be added we just need translations added in an iSite form. The only thing is that currently these translations are not used visually for the START and LIVE buttons due to space limitations on small devices. They are used however when read by a screen reader. Edmund White and the UX team were investigating removing the text from those buttons for some products.

There was little / no testing done outside of the UK so this potentially could be an issue. We could potentially load the player on a webpage outside of the UK and test the performance to see if it is better / worse and benchmark against our current player.

**Accessibility**

The new audio UI has been built with accessibility in mind so should be fully accessible.

Full spec for accessibility including tab order can be found here: https://confluence.dev.bbc.co.uk/display/mp/Audio+player+-+Accessibility+speccs

Documentation on the UI is here: https://confluence.dev.bbc.co.uk/display/mp/Using+the+Audio+UI

We may need to coordinate with UX / a11y to understand if there is sufficient a11y requirements for news. Catherine Green suggested doing an accessibility swarm following this checklist https://bbc-news.github.io/accessibility-news-and-you/accessibility-news-and-testers including testing with all our supported assistive technology. On completion of this we may have issues or requirements to raise with the team that built the audio player.

**RTL support**

Currently doesn't change anything apart from text direction. If we have preferences on how it should work for RTL languages we can add a feature request.

**Customisation**

Allows for easy changing of background and foreground colours.

Allows for customising skip increments e.g. 5 seconds, 20 seconds.

Autoplay supported which can work well for playlists.

**Comment by neildoughty** [comment] 2019-07-23 13:00
SMP already has WS translations in iSite - https://production.bbc.co.uk/isite2/p/smp-translations

Can/are these used in the audio 'skin'? Our current audio player is the video SMP, so potentially the perf bar we need to clear is already pretty low.

neil

**Comment by jroebu14** [comment] 2019-07-23 13:07
> Can/are these used in the audio 'skin'?

James Reed confirmed for me that, yes, those are the ones that are used.

**Comment by pjlee11** [comment] 2019-07-23 13:48
Good write up! Just a couple of thoughts:

Has there been any thought on internationalisation of the on-screen numbers? EG: to be non-latin such as eastern arabic numerals or western arabic numerals? 

How are the isite translations used? Do they prefix/suffix? Can they both prefix and suffix? 
NB: This might be a known limitation with default SMP already

**Comment by aeroplanejane** [comment] 2019-08-05 14:57
@jroebu14 We can probably close this I reckon - I don't think there's any further investigations we can carry out at this stage - we will raise issues / tickets for the necessary a11y fixes - thanks

**Closed as completed** 2019-08-05 14:57 UTC
Labels: investigation, ws-media
