### ISSUE TITLE
nanoid should not be used for keys in lists

### ISSUE THREAD

**Issue by jamesdonoh** [bbc/simorgh#1489] opened 2019-03-25 15:48 UTC
**Describe the bug**
We are currently using https://github.com/ai/nanoid to generate `key` props to uniquely identify children in some lists, however `nanoid` values are not stable. The docs for `nanoid` explicitly say not to do this: https://www.npmjs.com/package/nanoid#react

This hurts performance because it prevents React from making optimisations to avoid re-rendering more than it needs do, for more context see https://shripadk.github.io/react/docs/reconciliation.html#keys

Examples of using `nanoid`:
- https://github.com/bbc/simorgh/blob/latest/src/app/containers/Blocks/index.jsx#L23
- https://github.com/bbc/simorgh/blob/latest/src/app/components/ErrorPage/index.jsx#L52

**Expected behavior**
We should be using stable keys for item in lists for optimal render performance.

**Additional context**
Possibly relevant/related: https://github.com/bbc/simorgh/issues/1487

- [x] Initially labelled with ["bug"](https://github.com/bbc/simorgh/labels/bug)

**Comment by chris-hinds** [comment] 2019-04-02 08:19
Is it worth us asking Optimo to see if they can add a key to the data structure, at least for list items? This could be a hash of some data from the list item. The keys only need to be unique within the sub children and not globally. 

Otherwise I see us having to hydrate the Optimo data set before passing it to the relevant container where the key is applied.

**Comment by chris-hinds** [comment] 2019-04-02 09:33
According to the Optimo docs each block should have a UUID, however the current data feeds do not show this. I have asked to the Optimo team to clarify.

**Comment by chris-hinds** [comment] 2019-04-02 12:44
From Optimo

```
We removed them cos they weren't being used and were causing Optimo an issue within the editor because there isn't a 1:1 match between editor blocks and Optimo API blocks.

Don't expect them back any time soon. Sorry.
```

Looks like we will have to do something ourselves.

**Comment by ryanmccombe** [comment] 2019-06-03 15:52
Been looking at this with @jroebu14 as our first tickets to try to get a feel of how the application works

Current implementation of this will change the key every time the component renders, which is losing the benefit of keys

Things considered: 
1. Replacing Nano with a using array index as a key - generally an anti-pattern, but may be acceptable given the content isn't changing after the first render
2. Generating unique IDs at the point the data is retrieved
3. Generating unique IDs at the point the component that requires a key is mounted
4. Creating a hook to do option 3 in a functional component

I think we're leaning towards option 4 - welcome any feedback!

**Comment by jroebu14** [comment] 2019-06-05 08:47
Had a further discussion with Ryan and we don't think using a hook in this case is going to solve this problem. Our new proposed approach is to create a higher order component called something like `withKey` that returns a class component with a `key` property set outside of the render function so that it is not regenerated on every render. So something like this...

```javascript
import React, { Component } from 'react';
import nanoid from 'nanoid';

export default WrappedComponent =>
  class WithKey extends Component {
    key = nanoid();

    render() {
      return <WrappedComponent key={this.key} />;
    }
  };

```

and then in the Blocks component, for example, we can wrap the Block component like so

```javascript
    const Block = withKey(componentsToRender[type]);

    return (
      <Block type={type} typeOfPreviousBlock={typeOfPreviousBlock} {...model} />
    );
```

**Comment by ryanmccombe** [comment] 2019-06-05 15:29
Discovered the HoC method wasn't going to work, as it sets the key on the component it wraps, rather than the actual component that is being rendered from the `blocks.map` call

Also spent some time playing around with a generic wrapper that uses react.cloneElement to try to add the key to the top level element - that did work for the initial render, but we weren't able to keep the key the same in subsequent renders, so it really had the same problem as the existing solution

We might be over-thinking this to try to get a generic solution, rather than just adding IDs to the block data

We had a look at the below approach, which does seem to cover both concerns (adds IDs to the data, and the IDs don't change in subsequent renders):

```javascript
const Blocks = ({ blocks, componentsToRender }) => {
  // Adds an id property to every block that doesn't have one, so we have a key to use
  const [blocksWithIds] = useState(blocks.map(block => ({ ...block, id: block.id || nanoid()})));

  return blocksWithIds.map((block, index) => {
````
Another variant of this would involve just enriching the data with IDs at a lower level - eg, when it is first retrieved

**Comment by ryanmccombe** [comment] 2019-06-06 09:33
Confirmed the above approach does work with the current way the code is set up

@jroebu14 has generalised it into a reusable custom hook, with an API that works as cleanly as:

```javascript
useUniqueIds(blocks).map({} => {
    // do stuff
})
```

The issue we were talking about is that, if `blocks` changes at runtime, the keys do not get recalculated, so the rendered page does not change.  We're not sure it's possible to handle this case elegantly without converting some functional components to classes.

This is not a problem in the current code as the blocks do not change after first retrieval, but if it does happen in the future, there will be a nasty bug where the rendered article does not update, and it might not be immediately clear to developers why that is happening.

If this limitation is okay, we can work on implementing this approach properly with unit tests, and opening a PR

@jroebu14 @jamesdonoh @rossgaskell

**Comment by jroebu14** [comment] 2019-06-06 10:01
If we assume blocks data will never change after the first retrieval then I think using the array element index as the key is the simplest solution.

**Comment by ryanmccombe** [comment] 2019-06-06 10:47
It does seem inevitable that the future will involve the article blocks changing during app usage. 

eg, once users can navigate from article to article on the client side, react router will not teardown and rebuild the article container tree - it will just change the data that is being passed down through props.  This seems like a desirable behaviour for performance.

However, any code that assumes the article blocks are not changing will break in this scenario.  This includes the hooks code posted above, and I believe it also applies to index-based keys too

The only two solutions I can think of that will work in this scenario is mutating the blocks data after initial retrieval to add IDs, or switching to a class component that has the requisite lifecycle methods that will allow us to regenerate the keys only when the article blocks change, rather than on every render

**Comment by dr3** [comment] 2019-06-06 17:15
>mutating the blocks data after initial retrieval to add IDs

Just being nosey but this seems like it could be done nicely with a [preprocessor](https://github.com/bbc/simorgh/tree/latest/src/app/lib/utilities/preprocessor) rule

**Comment by jroebu14** [comment] 2019-06-07 08:04
My current thinking on this issue is that we have we have only 2 practical approaches.

### Use array element index as key
**Pros**
 - Assuming blocks is static and will never be reordered or filtered then this is safe to implement and satisfies our requirements.
 - Is a quick win and can easily be changed when requirements change, for example, if we use blocks for live-blogs in the future.

**Cons**
 - This is a glaring react anti-pattern.
 - If blocks data is not static then it can lead to unnecessary re-renders of each block and it's children.

### Mutate the blocks data after initial retrieval to add IDs
**Pros**
 - Solves all problems and doesn't introduce the index as key anti-pattern into the codebase which could set a bad example for futute devs.
 - This is the most performant solution if blocks are reorderable or filterable.
 - Solution could be reusable for other scenarios for lists that don't have a natural identifier.
 - As pointed out by @dr3 there are utitilies in the codebase that can help with the implementation.

**Cons**
 - Deep cloning and mutating blocks data might come with performance concerns as the data may be very nested.
 - If blocks data structure changes then the preprocessor rule has to change.
 - Requires a bit of work for something I feel we should be getting for free from Optimo :(

**Comment by jamesdonoh** [comment] 2019-06-07 09:37
As discussed at standup we're gonna go with the *Mutate the blocks data after initial retrieval* option as the best compromise under the circumstances as we won't be getting an ID from Optimo.

**Comment by ryanmccombe** [comment] 2019-06-19 13:00
There's a related PR here to also remove nanoid from Psammead: https://github.com/bbc/psammead/pull/604

Once this is released, we'll need to bump the dependency version in Simorgh to import the latest version

**Comment by ryanmccombe** [comment] 2019-06-28 13:20
> Once this is released, we'll need to bump the dependency version in Simorgh to import the latest version

This is captured as part of https://github.com/bbc/simorgh/pull/2084/ - once that PR is merged, this issue should be (finally!) done

**Closed as completed** 2019-06-28 13:49 UTC
Labels: bug, performance
